### ISSUE TITLE
Migrate to new build system

### ISSUE THREAD

**Issue by sardaukar** [thoughtbot/write-yourself-a-roguelike#28]
Right now, the book uses a build system that is not opensourced. One of the first challenges will be to transition away from it.

**Comment by jjasghar** [comment]
One option may be: https://www.gitbook.com/ we can consolidate a list here and work from there.

**Comment by ngscheurich** [comment]
#30 is relevant to this discussion.

**Comment by ngscheurich** [comment]
@sardaukar @jjasghar Please check out #33 and let me know what y'all think.

**Comment by sardaukar** [comment]
We might have a winner with #33 - a couple of issues, but a suitable epub comes out!

**Comment by ngscheurich** [comment]
#33 is now merged into master, so if we're comfortable moving forward with Pandoc, I think we can go ahead and close this.

**Comment by jjasghar** [comment]
Awesome. Great collaboration, looking forward to more!

**Comment by ngscheurich** [comment]
Good deal, guys. Closing this issue!
