### ISSUE TITLE
Automating typographic substitutions

### ISSUE THREAD

**Issue by ngscheurich** [thoughtbot/write-yourself-a-roguelike#31]
I think it would be useful to have some system in place to intelligently replace common approximations of typographic glyphs with their sometimes-hard-to-type-counterparts. I'm thinking things like:

* `---` or `--` to `—`
* `...` to `…`
* `'` to `’`
* `"` to `“` or `”` where appropriate

[`rubypants`](https://github.com/jmcnevin/rubypants) may be a library to consider using (for inspiration, at least).

Thoughts?

**Comment by ngscheurich** [comment]
I'll begin working on this.

**Comment by Trevoke** [comment]
The alternative is to actually be able to bring these in; any decent editor has support for UTF-8 input.

**Comment by Trevoke** [comment]
I mean, I say this, but I also have an emacs plugin that makes it incredibly easy to type these in, so I'm biased.

**Comment by ngscheurich** [comment]
Closing this for now. We can revisit it later if need be.
