### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by ngscheurich** [thoughtbot/write-yourself-a-roguelike#35]
Howdy all,

There hasn't been much movement on this project recently. I'd love to see us collaborate more frequently this year and hopefully bring this book to completion! If you've got some time to spare, check out the issues and PRs, or post a comment here with any thoughts you've got on some ways forward. Looking forward to getting some work done!

\- Nick

**Comment by Trevoke** [comment]
We have an outline, which is a nice start.

One significant thing to discuss is this tiny, tiny, almost insignificant blurb in the second section of the first chapter:

> As we build our roguelike, we will continously reference NetHack for both implementation and inspiration. We can do this because NetHack is open source, and while the code-base is almost 30 years old, I've gone ahead and spent countless hours using LLDB to figure out what's going on for you.

Do we have someone else who's done this?

Another significant thing to consider is whether we want to redo some of the work. I'm not sure to which extent we'll be able to extend reasonably the existing code when we get to things like status changes (poison, hunger, etc).

We might actually want to discuss bringing in a pattern like Entity-Component-Framework (ECS), which will make reasoning about these things easier.

**Comment by jjasghar** [comment]
I like the idea of referencing NetHack, it's a standard in the space. But, yes, we should remove the statement because finding someone with Ruby, writing, and "countless hours in the NetHack codebase," is a 🦄 .

I just say we remove this statement, and make a collaborative agreement to say any reference _should_ be NetHack not another rougelike.

**Comment by ngscheurich** [comment]
I definitely have not looked at any of the NetHack source. Perhaps moving forward we should agree to reference NetHack for inspiration but *not* implementation.

@Trevoke I'm fine with refactoring out into an ECS. Aside from the benefits you pointed out, that pattern's prevalence in gamedev and the current popularity of the Unity engine will make the architecture of our project easy to grasp for many experienced and aspiring game developers.

**Comment by Trevoke** [comment]
And by the way, it's absolutely worth noting that there is a large set of code in the `example_app` directory, so it's also worth considering whether we just need to break it down into its base code components and build a story around the reasoning for building the code, or whether we have to do more work.

**Comment by ngscheurich** [comment]
Recreating the existing game functionality to fit whatever the community's vision ends up being (whether its an ECS or not) doesn't seem like a terribly daunting task to me, if that's the direction we end up going.

**Comment by tvanderpol** [comment]
I'm very interested in the ongoing development of this project but I bought the book to learn the things that were listed as being part of the content. This means it'd be hard for me to help write the book!

I'm keen to do things like proof read or provide a perspective of someone who isn't well versed in game development.

**Comment by ngscheurich** [comment]
That's a super valuable perspective to bring to the project, @Trevoke, and I'm glad you're stoked to help out!

**Comment by ngscheurich** [comment]
Now that we've got the ball rolling and some folks actively involved, I'm going to go ahead and close this issue. Onward to adventure!
