### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by jjasghar** [thoughtbot/write-yourself-a-roguelike#36]
I might be crazy, but I don't see build instructions or how to use this code base.

I suggest a BUILDING.md and an "executive summary of steps" in the README.md.

Thoughts?

**Comment by ngscheurich** [comment]
You're right—there aren't currently any instructions for how to generate the book from source. I'll work on adding the BUILDING.md file (or perhaps just a section to the README?) that details this process.

Just for reference here: once you've cloned the repo, you should just need to run the `exe/compile` script to have a new EPUB placed in the `release` directory.

**Comment by ngscheurich** [comment]
This is done as of #38.
